// ========================================
// FOOD DATABASE - CHỈ DÀNH CHO AI SỬ DỤNG NỘI BỘ
// ========================================
// Database này chứa 100 món ăn fitness với thông tin macro chính xác
// KHÔNG hiển thị trực tiếp cho user, chỉ để AI tham chiếu khi tư vấn
// AI sẽ sử dụng data này để:
// - Lựa chọn món ăn phù hợp với mục tiêu user
// - Tính toán macros chính xác
// - Đưa ra gợi ý thực đơn khoa học
//
// CATEGORIES:
// - 20 món bò (ID 1-20)
// - 20 món heo (ID 21-40)
// - 20 món cá (ID 41-60)
// - 20 món gà (ID 61-80)
// - 10 món tinh bột (ID 81-90)
// - 10 healthy snacks (ID 91-100)
// ========================================

export interface FoodItem {
  id: number;
  name: string;
  category: "beef" | "pork" | "fish" | "chicken" | "starch" | "snack";
  ingredients: string;
  cookingMethod: string;
  calories: number;
  protein: number;
  carbs?: number;
  fat?: number;
  portionSize: string; // Định lượng chuẩn
}

export const FOOD_DATABASE: FoodItem[] = [
  // Danh sách 20 món bò (định lượng chuẩn 100g thịt bò/món)
  {
    id: 1,
    name: "Bò áp chảo tiêu tỏi",
    category: "beef",
    ingredients: "Tỏi 5g, tiêu, xíu dầu olive",
    cookingMethod: "Áp chảo lửa vừa 4–5 phút",
    calories: 140,
    protein: 22,
    portionSize: "100g thịt bò",
  },
  {
    id: 2,
    name: "Bò xào bông cải xanh",
    category: "beef",
    ingredients: "Bông cải 100g, tỏi",
    cookingMethod: "Xào nhanh 5 phút",
    calories: 160,
    protein: 23,
    portionSize: "100g thịt bò",
  },
  {
    id: 3,
    name: "Bò cuộn măng tây",
    category: "beef",
    ingredients: "Măng tây 50g, tiêu đen",
    cookingMethod: "Cuộn – áp chảo",
    calories: 150,
    protein: 22,
    portionSize: "100g thịt bò",
  },
  {
    id: 4,
    name: "Bò hấp gừng",
    category: "beef",
    ingredients: "Gừng lát, hành, tiêu",
    cookingMethod: "Hấp cách thủy 15'",
    calories: 135,
    protein: 23,
    portionSize: "100g thịt bò",
  },
  {
    id: 5,
    name: "Bò xào ớt chuông",
    category: "beef",
    ingredients: "Ớt chuông đỏ vàng 80g",
    cookingMethod: "Xào nhanh lửa lớn",
    calories: 170,
    protein: 22,
    portionSize: "100g thịt bò",
  },
  {
    id: 6,
    name: "Bò luộc chấm muối chanh",
    category: "beef",
    ingredients: "Muối hồng, chanh, ớt",
    cookingMethod: "Luộc mềm vừa",
    calories: 130,
    protein: 22,
    portionSize: "100g thịt bò",
  },
  {
    id: 7,
    name: "Bò sốt tiêu đen",
    category: "beef",
    ingredients: "Tiêu đen, hành tím, nước tương ít natri",
    cookingMethod: "Áp chảo & đun sốt",
    calories: 160,
    protein: 21,
    portionSize: "100g thịt bò",
  },
  {
    id: 8,
    name: "Bò nướng giấy bạc",
    category: "beef",
    ingredients: "Tỏi, hành, ít dầu mè",
    cookingMethod: "Nướng 180°C – 10'",
    calories: 150,
    protein: 23,
    portionSize: "100g thịt bò",
  },
  {
    id: 9,
    name: "Salad bò trộn mè rang",
    category: "beef",
    ingredients: "Rau xà lách, dưa leo, cà rốt, mè",
    cookingMethod: "Áp chảo bò – trộn",
    calories: 180,
    protein: 21,
    portionSize: "100g thịt bò",
  },
  {
    id: 10,
    name: "Bò kho gừng ít nước",
    category: "beef",
    ingredients: "Gừng, hành, tiêu, nước mắm nhạt",
    cookingMethod: "Kho ít nước 10'",
    calories: 170,
    protein: 22,
    portionSize: "100g thịt bò",
  },
  {
    id: 11,
    name: "Bò xào hành cần",
    category: "beef",
    ingredients: "Hành tây, cần tây, tỏi",
    cookingMethod: "Xào nhanh 3–5 phút",
    calories: 160,
    protein: 21,
    portionSize: "100g thịt bò",
  },
  {
    id: 12,
    name: "Bò nhúng giấm rau sống",
    category: "beef",
    ingredients: "Giấm, hành tím, rau",
    cookingMethod: "Nhúng chín tới",
    calories: 140,
    protein: 23,
    portionSize: "100g thịt bò",
  },
  {
    id: 13,
    name: "Bò nướng xiên rau củ",
    category: "beef",
    ingredients: "Cà tím, ớt, hành tây",
    cookingMethod: "Xiên nướng lò / than",
    calories: 170,
    protein: 22,
    portionSize: "100g thịt bò",
  },
  {
    id: 14,
    name: "Bò xào nấm",
    category: "beef",
    ingredients: "Nấm đùi gà hoặc nấm đông cô 100g",
    cookingMethod: "Xào vừa chín",
    calories: 160,
    protein: 21,
    portionSize: "100g thịt bò",
  },
  {
    id: 15,
    name: "Bò lá lốt nướng (ít dầu)",
    category: "beef",
    ingredients: "Lá lốt 8 lá, tiêu",
    cookingMethod: "Cuộn nướng khô",
    calories: 180,
    protein: 20,
    portionSize: "100g thịt bò",
  },
  {
    id: 16,
    name: "Bò cuộn trứng chiên ít dầu",
    category: "beef",
    ingredients: "Trứng 1 quả, hành, tiêu",
    cookingMethod: "Cuộn – áp chảo",
    calories: 200,
    protein: 21,
    portionSize: "100g thịt bò",
  },
  {
    id: 17,
    name: "Bò khoai tây áp chảo",
    category: "beef",
    ingredients: "Khoai tây luộc 100g",
    cookingMethod: "Áp chảo với bò",
    calories: 220,
    protein: 21,
    portionSize: "100g thịt bò",
  },
  {
    id: 18,
    name: "Cháo bò cà rốt",
    category: "beef",
    ingredients: "Gạo tấm 20g, cà rốt 50g",
    cookingMethod: "Ninh nhừ 30'",
    calories: 180,
    protein: 18,
    portionSize: "100g thịt bò",
  },
  {
    id: 19,
    name: "Phở bò healthy",
    category: "beef",
    ingredients: "Bánh phở 50g, hành, rau thơm",
    cookingMethod: "Chan nước dùng trong",
    calories: 220,
    protein: 17,
    portionSize: "100g thịt bò",
  },
  {
    id: 20,
    name: "Canh bò rau củ",
    category: "beef",
    ingredients: "Bò nạc 100g, cà rốt, củ cải",
    cookingMethod: "Ninh mềm",
    calories: 160,
    protein: 20,
    portionSize: "100g thịt bò",
  },

  // Danh sách 20 món thịt heo (định lượng chuẩn 100g thịt/món)
  {
    id: 21,
    name: "Heo luộc gừng",
    category: "pork",
    ingredients: "Gừng lát, muối hồng",
    cookingMethod: "Luộc mềm vừa",
    calories: 150,
    protein: 21,
    portionSize: "100g thịt heo",
  },
  {
    id: 22,
    name: "Thịt heo áp chảo tỏi",
    category: "pork",
    ingredients: "Tỏi, tiêu, dầu oliu 3g",
    cookingMethod: "Áp chảo lửa vừa",
    calories: 170,
    protein: 20,
    portionSize: "100g thịt heo",
  },
  {
    id: 23,
    name: "Thịt nạc kho nghệ",
    category: "pork",
    ingredients: "Nghệ tươi, tiêu, hành tím",
    cookingMethod: "Kho ít nước",
    calories: 165,
    protein: 21,
    portionSize: "100g thịt heo",
  },
  {
    id: 24,
    name: "Thịt heo hấp nấm",
    category: "pork",
    ingredients: "Nấm rơm/nấm kim châm 80g",
    cookingMethod: "Hấp cách thủy",
    calories: 160,
    protein: 20,
    portionSize: "100g thịt heo",
  },
  {
    id: 25,
    name: "Salad thịt heo trộn mè",
    category: "pork",
    ingredients: "Rau sống, mè rang, nước tương ít",
    cookingMethod: "Luộc + trộn salad",
    calories: 180,
    protein: 19,
    portionSize: "100g thịt heo",
  },
  {
    id: 26,
    name: "Thịt heo cuộn cải bẹ",
    category: "pork",
    ingredients: "Cải bẹ, hành lá, gừng",
    cookingMethod: "Hấp hoặc luộc",
    calories: 160,
    protein: 20,
    portionSize: "100g thịt heo",
  },
  {
    id: 27,
    name: "Canh thịt heo rau củ",
    category: "pork",
    ingredients: "Cà rốt, củ cải, hành",
    cookingMethod: "Nấu canh lửa nhỏ",
    calories: 150,
    protein: 19,
    portionSize: "100g thịt heo",
  },
  {
    id: 28,
    name: "Thịt nạc rim tiêu",
    category: "pork",
    ingredients: "Tiêu, nước mắm ít, hành",
    cookingMethod: "Rim 7–10 phút",
    calories: 170,
    protein: 20,
    portionSize: "100g thịt heo",
  },
  {
    id: 29,
    name: "Heo xào đậu que",
    category: "pork",
    ingredients: "Đậu que 100g, tỏi",
    cookingMethod: "Xào nhanh ít dầu",
    calories: 180,
    protein: 19,
    portionSize: "100g thịt heo",
  },
  {
    id: 30,
    name: "Thịt heo xào cải thìa",
    category: "pork",
    ingredients: "Cải thìa 80g, tỏi",
    cookingMethod: "Xào nhanh",
    calories: 170,
    protein: 20,
    portionSize: "100g thịt heo",
  },
  {
    id: 31,
    name: "Thịt heo nướng xiên rau",
    category: "pork",
    ingredients: "Ớt chuông, hành tây, tiêu",
    cookingMethod: "Xiên – nướng lò",
    calories: 190,
    protein: 19,
    portionSize: "100g thịt heo",
  },
  {
    id: 32,
    name: "Thịt kho trứng (ít mỡ)",
    category: "pork",
    ingredients: "Trứng ½ quả, nước mắm nhạt",
    cookingMethod: "Kho 20 phút",
    calories: 220,
    protein: 18,
    portionSize: "100g thịt heo",
  },
  {
    id: 33,
    name: "Thịt heo nướng sả",
    category: "pork",
    ingredients: "Sả băm, tiêu, dầu vừng",
    cookingMethod: "Nướng than/lò",
    calories: 180,
    protein: 20,
    portionSize: "100g thịt heo",
  },
  {
    id: 34,
    name: "Heo cuộn măng tây",
    category: "pork",
    ingredients: "Măng tây 60g, tiêu",
    cookingMethod: "Áp chảo không dầu",
    calories: 170,
    protein: 20,
    portionSize: "100g thịt heo",
  },
  {
    id: 35,
    name: "Heo áp chảo sốt cà chua",
    category: "pork",
    ingredients: "Cà chua ½ quả, tiêu, hành",
    cookingMethod: "Nấu sệt sốt",
    calories: 180,
    protein: 19,
    portionSize: "100g thịt heo",
  },
  {
    id: 36,
    name: "Thịt xào mướp hương",
    category: "pork",
    ingredients: "Mướp 100g, hành",
    cookingMethod: "Xào nhanh 3 phút",
    calories: 160,
    protein: 18,
    portionSize: "100g thịt heo",
  },
  {
    id: 37,
    name: "Heo hấp lá chanh",
    category: "pork",
    ingredients: "Lá chanh, gừng",
    cookingMethod: "Hấp đơn giản",
    calories: 150,
    protein: 20,
    portionSize: "100g thịt heo",
  },
  {
    id: 38,
    name: "Cháo thịt bằm cà rốt",
    category: "pork",
    ingredients: "Gạo 20g, cà rốt 50g",
    cookingMethod: "Ninh nhừ",
    calories: 180,
    protein: 17,
    portionSize: "100g thịt heo",
  },
  {
    id: 39,
    name: "Bún thịt heo luộc",
    category: "pork",
    ingredients: "Bún tươi 50g, rau sống",
    cookingMethod: "Luộc thịt + trộn",
    calories: 220,
    protein: 17,
    portionSize: "100g thịt heo",
  },
  {
    id: 40,
    name: "Thịt heo cuộn trứng hấp",
    category: "pork",
    ingredients: "Trứng gà 1 quả, tiêu",
    cookingMethod: "Hấp cách thủy",
    calories: 210,
    protein: 18,
    portionSize: "100g thịt heo",
  },

  // Danh sách 20 món cá (định lượng chuẩn 100g thịt/món)
  {
    id: 41,
    name: "Cá hồi áp chảo",
    category: "fish",
    ingredients: "Tiêu, tỏi, dầu oliu 3g",
    cookingMethod: "Áp chảo lửa vừa",
    calories: 200,
    protein: 20,
    portionSize: "100g cá",
  },
  {
    id: 42,
    name: "Cá hồi nướng chanh",
    category: "fish",
    ingredients: "Chanh tươi, tiêu, lá thyme (tùy chọn)",
    cookingMethod: "Nướng lò 10–12'",
    calories: 190,
    protein: 21,
    portionSize: "100g cá",
  },
  {
    id: 43,
    name: "Cá basa hấp gừng",
    category: "fish",
    ingredients: "Gừng lát, hành lá",
    cookingMethod: "Hấp 10 phút",
    calories: 130,
    protein: 18,
    portionSize: "100g cá",
  },
  {
    id: 44,
    name: "Cá rô phi áp chảo",
    category: "fish",
    ingredients: "Tỏi, tiêu, xíu dầu",
    cookingMethod: "Áp chảo 2 mặt",
    calories: 150,
    protein: 22,
    portionSize: "100g cá",
  },
  {
    id: 45,
    name: "Cá thu kho tiêu",
    category: "fish",
    ingredients: "Tiêu đen, nước mắm ít",
    cookingMethod: "Kho nhanh 10'",
    calories: 180,
    protein: 20,
    portionSize: "100g cá",
  },
  {
    id: 46,
    name: "Cá nướng muối ớt",
    category: "fish",
    ingredients: "Muối hồng, ớt bột",
    cookingMethod: "Nướng than/lò",
    calories: 170,
    protein: 21,
    portionSize: "100g cá",
  },
  {
    id: 47,
    name: "Cá ngừ áp chảo",
    category: "fish",
    ingredients: "Tiêu, dầu oliu",
    cookingMethod: "Áp chảo vừa chín",
    calories: 160,
    protein: 23,
    portionSize: "100g cá",
  },
  {
    id: 48,
    name: "Cá hấp cải bẹ",
    category: "fish",
    ingredients: "Cải bẹ, gừng, tiêu",
    cookingMethod: "Hấp cách thủy",
    calories: 140,
    protein: 20,
    portionSize: "100g cá",
  },
  {
    id: 49,
    name: "Cá sốt cà chua",
    category: "fish",
    ingredients: "Cà chua ½ quả, hành tím",
    cookingMethod: "Nấu sốt",
    calories: 170,
    protein: 20,
    portionSize: "100g cá",
  },
  {
    id: 50,
    name: "Cá kho nghệ",
    category: "fish",
    ingredients: "Nghệ tươi, tiêu",
    cookingMethod: "Kho ít nước",
    calories: 160,
    protein: 21,
    portionSize: "100g cá",
  },
  {
    id: 51,
    name: "Cá nướng giấy bạc",
    category: "fish",
    ingredients: "Tỏi, hành, rau thơm",
    cookingMethod: "Nướng lò 180°C 10'",
    calories: 160,
    protein: 20,
    portionSize: "100g cá",
  },
  {
    id: 52,
    name: "Salad cá hồi xé",
    category: "fish",
    ingredients: "Xà lách, dưa leo, sốt mè",
    cookingMethod: "Trộn nguội",
    calories: 200,
    protein: 19,
    portionSize: "100g cá",
  },
  {
    id: 53,
    name: "Cá rô phi nướng lá chuối",
    category: "fish",
    ingredients: "Lá chuối, tiêu",
    cookingMethod: "Nướng than hoặc lò",
    calories: 150,
    protein: 20,
    portionSize: "100g cá",
  },
  {
    id: 54,
    name: "Canh chua cá lóc (ít me)",
    category: "fish",
    ingredients: "Cà chua, dứa, bạc hà",
    cookingMethod: "Nấu canh trong",
    calories: 140,
    protein: 18,
    portionSize: "100g cá",
  },
  {
    id: 55,
    name: "Cá hấp chanh ớt",
    category: "fish",
    ingredients: "Chanh, ớt, hành, gừng",
    cookingMethod: "Hấp cay nhẹ",
    calories: 150,
    protein: 21,
    portionSize: "100g cá",
  },
  {
    id: 56,
    name: "Cá viên hấp homemade",
    category: "fish",
    ingredients: "Cá xay 100g, tiêu, xíu bột năng",
    cookingMethod: "Viên hấp 10 phút",
    calories: 160,
    protein: 22,
    portionSize: "100g cá",
  },
  {
    id: 57,
    name: "Cá basa áp chảo sốt tiêu",
    category: "fish",
    ingredients: "Tiêu, nước mắm ít, hành",
    cookingMethod: "Áp chảo – rưới sốt",
    calories: 170,
    protein: 20,
    portionSize: "100g cá",
  },
  {
    id: 58,
    name: "Cá thu nướng mù tạt",
    category: "fish",
    ingredients: "Mù tạt vàng, tiêu",
    cookingMethod: "Nướng khô 10'",
    calories: 180,
    protein: 21,
    portionSize: "100g cá",
  },
  {
    id: 59,
    name: "Cá hấp hành thì là",
    category: "fish",
    ingredients: "Hành, thì là, tiêu",
    cookingMethod: "Hấp 10–12 phút",
    calories: 150,
    protein: 20,
    portionSize: "100g cá",
  },
  {
    id: 60,
    name: "Cá ngừ cuộn rau sống",
    category: "fish",
    ingredients: "Cá luộc xé, rau xà lách, dưa leo",
    cookingMethod: "Cuộn + nước chấm",
    calories: 160,
    protein: 22,
    portionSize: "100g cá",
  },

  // Danh sách 20 món gà (chuẩn 100g thịt/món)
  {
    id: 61,
    name: "Ức gà áp chảo tiêu tỏi",
    category: "chicken",
    ingredients: "Tỏi, tiêu đen, dầu oliu 3g",
    cookingMethod: "Áp chảo vàng 2 mặt",
    calories: 165,
    protein: 23,
    portionSize: "100g thịt gà",
  },
  {
    id: 62,
    name: "Ức gà luộc chấm muối tiêu chanh",
    category: "chicken",
    ingredients: "Muối hồng, tiêu, chanh",
    cookingMethod: "Luộc mềm",
    calories: 150,
    protein: 24,
    portionSize: "100g thịt gà",
  },
  {
    id: 63,
    name: "Gà nướng giấy bạc",
    category: "chicken",
    ingredients: "Hành, tỏi, tiêu, ít dầu",
    cookingMethod: "Nướng 180°C 15–20 phút",
    calories: 170,
    protein: 23,
    portionSize: "100g thịt gà",
  },
  {
    id: 64,
    name: "Gà xào bông cải xanh",
    category: "chicken",
    ingredients: "Bông cải 100g, tỏi",
    cookingMethod: "Xào nhanh ít dầu",
    calories: 180,
    protein: 22,
    portionSize: "100g thịt gà",
  },
  {
    id: 65,
    name: "Gà hấp gừng",
    category: "chicken",
    ingredients: "Gừng lát, hành lá",
    cookingMethod: "Hấp cách thủy",
    calories: 160,
    protein: 24,
    portionSize: "100g thịt gà",
  },
  {
    id: 66,
    name: "Salad ức gà trộn mè",
    category: "chicken",
    ingredients: "Rau sống, cà chua, mè rang",
    cookingMethod: "Trộn nguội",
    calories: 190,
    protein: 22,
    portionSize: "100g thịt gà",
  },
  {
    id: 67,
    name: "Gà cuộn măng tây",
    category: "chicken",
    ingredients: "Măng tây 60g, tiêu",
    cookingMethod: "Áp chảo",
    calories: 170,
    protein: 22,
    portionSize: "100g thịt gà",
  },
  {
    id: 68,
    name: "Ức gà sốt cà chua",
    category: "chicken",
    ingredients: "Cà chua ½ quả, tiêu, hành",
    cookingMethod: "Nấu sốt sệt",
    calories: 180,
    protein: 21,
    portionSize: "100g thịt gà",
  },
  {
    id: 69,
    name: "Gà xào ớt chuông",
    category: "chicken",
    ingredients: "Ớt chuông 100g, hành tây",
    cookingMethod: "Xào vừa chín",
    calories: 180,
    protein: 22,
    portionSize: "100g thịt gà",
  },
  {
    id: 70,
    name: "Canh gà nấm",
    category: "chicken",
    ingredients: "Nấm rơm 80g, hành, gừng",
    cookingMethod: "Nấu canh trong",
    calories: 160,
    protein: 21,
    portionSize: "100g thịt gà",
  },
  {
    id: 71,
    name: "Gà nướng sả",
    category: "chicken",
    ingredients: "Sả băm, tiêu, dầu vừng",
    cookingMethod: "Ướp & nướng",
    calories: 180,
    protein: 22,
    portionSize: "100g thịt gà",
  },
  {
    id: 72,
    name: "Cháo gà cà rốt",
    category: "chicken",
    ingredients: "Gạo tấm 20g, cà rốt 50g",
    cookingMethod: "Ninh nhừ",
    calories: 170,
    protein: 18,
    portionSize: "100g thịt gà",
  },
  {
    id: 73,
    name: "Cơm gà healthy",
    category: "chicken",
    ingredients: "Cơm gạo lứt 80g, rau luộc",
    cookingMethod: "Ăn kèm ức gà luộc",
    calories: 370,
    protein: 22,
    portionSize: "100g thịt gà",
  },
  {
    id: 74,
    name: "Gà xào nấm",
    category: "chicken",
    ingredients: "Nấm đùi gà hoặc nấm đông cô",
    cookingMethod: "Xào 5 phút",
    calories: 170,
    protein: 21,
    portionSize: "100g thịt gà",
  },
  {
    id: 75,
    name: "Ức gà chiên không dầu",
    category: "chicken",
    ingredients: "Bột tỏi, bột ớt, nồi chiên",
    cookingMethod: "180°C – 10'",
    calories: 170,
    protein: 22,
    portionSize: "100g thịt gà",
  },
  {
    id: 76,
    name: "Ức gà cuộn trứng hấp",
    category: "chicken",
    ingredients: "Trứng 1 quả, hành",
    cookingMethod: "Hấp 10–15 phút",
    calories: 200,
    protein: 20,
    portionSize: "100g thịt gà",
  },
  {
    id: 77,
    name: "Gà kho nghệ",
    category: "chicken",
    ingredients: "Nghệ, nước mắm ít natri",
    cookingMethod: "Kho cạn nước",
    calories: 180,
    protein: 22,
    portionSize: "100g thịt gà",
  },
  {
    id: 78,
    name: "Gà trộn bắp cải",
    category: "chicken",
    ingredients: "Bắp cải tím + trắng, mè rang",
    cookingMethod: "Trộn nguội",
    calories: 190,
    protein: 20,
    portionSize: "100g thịt gà",
  },
  {
    id: 79,
    name: "Gà nướng lá chanh",
    category: "chicken",
    ingredients: "Lá chanh, tiêu, muối",
    cookingMethod: "Nướng lửa vừa",
    calories: 170,
    protein: 22,
    portionSize: "100g thịt gà",
  },
  {
    id: 80,
    name: "Gà nhúng giấm cuốn rau",
    category: "chicken",
    ingredients: "Giấm loãng, rau sống",
    cookingMethod: "Luộc vừa chín",
    calories: 160,
    protein: 23,
    portionSize: "100g thịt gà",
  },

  // Danh sách 10 món thuộc nhóm tinh bột (định lượng chuẩn 100g/món)
  {
    id: 81,
    name: "Gạo lứt chín",
    category: "starch",
    ingredients: "Gạo lứt",
    cookingMethod: "Nấu cơm",
    calories: 111,
    protein: 2.6,
    carbs: 23.0,
    fat: 0.9,
    portionSize: "100g",
  },
  {
    id: 82,
    name: "Khoai lang luộc",
    category: "starch",
    ingredients: "Khoai lang",
    cookingMethod: "Luộc chín",
    calories: 86,
    protein: 1.6,
    carbs: 20.1,
    fat: 0.1,
    portionSize: "100g",
  },
  {
    id: 83,
    name: "Yến mạch nấu (oatmeal)",
    category: "starch",
    ingredients: "Yến mạch",
    cookingMethod: "Nấu với nước",
    calories: 71,
    protein: 2.5,
    carbs: 12.0,
    fat: 1.5,
    portionSize: "100g",
  },
  {
    id: 84,
    name: "Bánh mì nguyên cám (nướng)",
    category: "starch",
    ingredients: "Bánh mì nguyên cám",
    cookingMethod: "Nướng",
    calories: 247,
    protein: 8.7,
    carbs: 41.0,
    fat: 4.4,
    portionSize: "100g",
  },
  {
    id: 85,
    name: "Nui gạo lứt luộc",
    category: "starch",
    ingredients: "Nui gạo lứt",
    cookingMethod: "Luộc chín",
    calories: 111,
    protein: 2.4,
    carbs: 24.0,
    fat: 0.9,
    portionSize: "100g",
  },
  {
    id: 86,
    name: "Miến dong chín",
    category: "starch",
    ingredients: "Miến dong",
    cookingMethod: "Luộc",
    calories: 66,
    protein: 0.1,
    carbs: 16.7,
    fat: 0.1,
    portionSize: "100g",
  },
  {
    id: 87,
    name: "Đậu đỏ hầm (chín)",
    category: "starch",
    ingredients: "Đậu đỏ",
    cookingMethod: "Hầm chín",
    calories: 127,
    protein: 8.7,
    carbs: 23.7,
    fat: 0.5,
    portionSize: "100g",
  },
  {
    id: 88,
    name: "Ngô (bắp) luộc",
    category: "starch",
    ingredients: "Ngô",
    cookingMethod: "Luộc",
    calories: 96,
    protein: 3.4,
    carbs: 21.0,
    fat: 1.5,
    portionSize: "100g",
  },
  {
    id: 89,
    name: "Quinoa chín",
    category: "starch",
    ingredients: "Quinoa",
    cookingMethod: "Nấu chín",
    calories: 120,
    protein: 4.1,
    carbs: 21.3,
    fat: 1.9,
    portionSize: "100g",
  },
  {
    id: 90,
    name: "Cơm tấm (ít dẻo)",
    category: "starch",
    ingredients: "Gạo tấm",
    cookingMethod: "Nấu cơm",
    calories: 109,
    protein: 2.2,
    carbs: 24.2,
    fat: 0.3,
    portionSize: "100g",
  },

  // ========================================
  // DANH SÁCH 10 HEALTHY SNACKS (ID 91-100)
  // ========================================
  // Các món snack healthy thiên ngọt - ít đường - giàu protein
  // Phù hợp cho người tập luyện và mục tiêu fitness

  {
    id: 91,
    name: "Greek yogurt không đường với trái cây",
    category: "snack",
    ingredients: "Greek yogurt không đường 100g, trái cây tươi 50g (dâu/chuối)",
    cookingMethod: "Trộn đều, ăn ngay",
    calories: 110,
    protein: 12,
    carbs: 8,
    fat: 3,
    portionSize: "150g (100g yogurt + 50g trái cây)",
  },
  {
    id: 92,
    name: "Trứng luộc với cacao nguyên chất",
    category: "snack",
    ingredients: "1 trứng gà luộc, ½ muỗng cà phê bột cacao nguyên chất",
    cookingMethod: "Luộc trứng chín, rắc cacao",
    calories: 80,
    protein: 6,
    carbs: 0.5,
    fat: 5,
    portionSize: "1 trứng + ½ tsp cacao",
  },
  {
    id: 93,
    name: "Protein bar homemade yến mạch",
    category: "snack",
    ingredients: "Yến mạch 30g, whey protein 15g, bơ đậu phộng 10g",
    cookingMethod: "Trộn đều, nặn thành thanh, ướp lạnh 30 phút",
    calories: 160,
    protein: 14,
    carbs: 12,
    fat: 6,
    portionSize: "1 thanh (55g)",
  },
  {
    id: 94,
    name: "Cottage cheese với mật ong",
    category: "snack",
    ingredients:
      "Cottage cheese 100g, mật ong 1 muỗng cà phê hoặc trái cây tươi",
    cookingMethod: "Trộn đều, ăn ngay",
    calories: 130,
    protein: 12,
    carbs: 8,
    fat: 5,
    portionSize: "100g cottage cheese + topping",
  },
  {
    id: 95,
    name: "Pancake yến mạch protein mini",
    category: "snack",
    ingredients:
      "Yến mạch xay 40g, whey protein 20g, trứng 1 quả, sữa hạt 50ml",
    cookingMethod: "Trộn bột, chiên chảo không dầu 3 bánh nhỏ",
    calories: 200,
    protein: 20,
    carbs: 18,
    fat: 6,
    portionSize: "3 bánh nhỏ",
  },
  {
    id: 96,
    name: "Chuối với bơ đậu phộng",
    category: "snack",
    ingredients: "½ quả chuối chín, bơ đậu phộng tự nhiên 10g",
    cookingMethod: "Thái chuối, chấm bơ đậu phộng",
    calories: 120,
    protein: 4,
    carbs: 12,
    fat: 6,
    portionSize: "½ chuối + 10g bơ đậu phộng",
  },
  {
    id: 97,
    name: "Sữa chua Hy Lạp với hạt điều",
    category: "snack",
    ingredients: "Sữa chua Hy Lạp 100g, bột quế, hạt điều 10g",
    cookingMethod: "Trộn đều, rắc hạt điều và quế",
    calories: 140,
    protein: 10,
    carbs: 6,
    fat: 8,
    portionSize: "100g sữa chua + 10g hạt điều",
  },
  {
    id: 98,
    name: "Đậu gà rang với cacao",
    category: "snack",
    ingredients: "Đậu gà chín 50g, bột cacao hoặc bột quế",
    cookingMethod: "Rang khô đậu gà, rắc gia vị",
    calories: 120,
    protein: 6,
    carbs: 18,
    fat: 2,
    portionSize: "50g đậu gà chín",
  },
  {
    id: 99,
    name: "Flan lòng trắng trứng protein",
    category: "snack",
    ingredients: "2 lòng trắng trứng, sữa hạt không đường 50ml, stevia",
    cookingMethod: "Đánh đều, hấp cách thủy 10-15 phút",
    calories: 100,
    protein: 11,
    carbs: 3,
    fat: 2,
    portionSize: "1 cup flan (2 lòng trắng)",
  },
  {
    id: 100,
    name: "Sinh tố protein chuối",
    category: "snack",
    ingredients: "Whey protein 1 scoop (30g), ½ chuối, sữa hạnh nhân 200ml",
    cookingMethod: "Xay sinh tố, uống ngay",
    calories: 180,
    protein: 23,
    carbs: 8,
    fat: 4,
    portionSize: "1 ly 250ml",
  },
];

// ========================================
// UTILITY FUNCTIONS - CHỈ CHO AI SỬ DỤNG NỘI BỘ
// ========================================
// Các function này giúp AI tìm kiếm và lọc dữ liệu từ food database
// KHÔNG expose ra UI cho user

// Utility functions for searching and filtering
export const getFoodsByCategory = (
  category: FoodItem["category"]
): FoodItem[] => {
  return FOOD_DATABASE.filter((food) => food.category === category);
};

export const searchFoodsByName = (searchTerm: string): FoodItem[] => {
  return FOOD_DATABASE.filter((food) =>
    food.name.toLowerCase().includes(searchTerm.toLowerCase())
  );
};

export const getFoodById = (id: number): FoodItem | undefined => {
  return FOOD_DATABASE.find((food) => food.id === id);
};

export const getAllCategories = (): string[] => {
  return ["beef", "pork", "fish", "chicken", "starch"];
};

export const getCategoryDisplayName = (category: string): string => {
  const displayNames: Record<string, string> = {
    beef: "Món Bò",
    pork: "Món Heo",
    fish: "Món Cá",
    chicken: "Món Gà",
    starch: "Tinh Bột",
    snack: "Healthy Snacks",
  };
  return displayNames[category] || category;
};

// Calculate macros for custom portions - AI dùng để tính toán khi user muốn khẩu phần khác 100g
export const calculateMacros = (food: FoodItem, portionGrams: number) => {
  const ratio = portionGrams / 100; // Since all data is per 100g
  return {
    calories: Math.round(food.calories * ratio),
    protein: Math.round(food.protein * ratio * 10) / 10,
    carbs: food.carbs ? Math.round(food.carbs * ratio * 10) / 10 : undefined,
    fat: food.fat ? Math.round(food.fat * ratio * 10) / 10 : undefined,
  };
};
